### ISSUE TITLE
Normalize client_Id

### ISSUE THREAD

**Issue by martymcguire** [Taproot/indieauth#12]
Thanks for this! I'm using it to make a standalone IndieAuth server (and plan to publish it for others to use as a template once I switch from "bang it together until it works" mode and clean things up a little.

[OwnCast](https://owncast.online/) recently added IndieAuth support for signing into their chat system. However, they pass `client_id` as a URL with scheme and host only, no path component: https://github.com/owncast/owncast/blob/develop/auth/indieauth/helpers.go#L39

Taproot/indieauth treats this as a hard failure and refuses to proceed.

Chatted about this in `#indieweb-dev` and aaronpk pointed out that the URL canonicalization section in the IndieAuth spec refers to all URLs, not just `me` URLs.

- start of relevant chat: https://chat.indieweb.org/dev/2022-07-28#t1659023548487400
- https://indieauth.spec.indieweb.org/#url-canonicalization

Here's a quick and dirty set of hacks I made to get my own instance working. I'd love to know your thoughts on this (or other) approaches before I turn this into a PR!

https://github.com/martymcguire/taproot-indieauth/commit/66cf81ac3ce3c6e666ef941ac5caeafa914fc470

I don't love the duplication of code, but it kind of follows how the `me` param gets normalized.

I also added a normalization step for `client_id` when computing the hash for the authorization form. The function gets passed the whole request object and pulls the query params fresh.

Thanks again!

**Comment by martymcguire** [comment]
A quick followup: I've since reverted this in favor of normalizing `client_id` in the query string or body params before passing the modified `$request` off to taproot/indieauth.

**Comment by barnabywalters** [comment]
Glad the library is useful for someone, I must admit I still haven’t had time to integrate it into my personal site.

Good that there’s a workaround, but failing on URLs with missing path components still sounds like a bug with the library to me, so I’ll try to take a look at it soon.

**Comment by martymcguire** [comment]
I realized I forgot to share the actual workaround I have for this once I published the code.

Here in my routes setup I wrap all my routes that will eventually go to taproot/indieauth with a middleware to normalize the client ID: https://git.schmarty.net/schmarty/belding/src/branch/main/public/index.php#L58-L69

Here's that actual middleware: https://git.schmarty.net/schmarty/belding/src/branch/main/app/Middleware/NormalizeClientIdMiddleware.php

And for good measure the controller that actually makes calls to taproot/indieauth: https://git.schmarty.net/schmarty/belding/src/branch/main/app/Controller.php

**Comment by barnabywalters** [comment]
Discussed this normalization a bit in the chat https://chat.indieweb.org/dev/2022-09-04#t1662282371251700

Conclusions:
* redirect_uri should be normalized to include a path if empty. Non-http(s) schemes are accepted
* client_id should be normalized to include a path if empty.
* Neither may include a fragment

Open questions:
* In cases where provided client_id and redirect_uri are compared to the stored version, is comparing normalized versions acceptable? Required? Do we have to store both normalized and non-normalized versions of the fields?

cc @zegnat @aaronpk

**Comment by martymcguire** [comment]
@barnabywalters adding my 0.02¢ here that my middleware example above normalizes `client_id` on every endpoint where it can be passed in as a query argument, and only the normalized version is ever stored or compared.

**Comment by barnabywalters** [comment]
From #indieweb-dev discussion: decided that the best method for now is to store and compare the given values as opaque strings, and lazily perform normalization when validating and fetching client_id and redirect_uri.
