### ISSUE TITLE
Allow `.` and `~` in `code_challenge`

### ISSUE THREAD

**Issue by martymcguire** [Taproot/indieauth#13]
https://indieauth.spec.indieweb.org/#authorization-request references https://datatracker.ietf.org/doc/html/rfc7636 which has [this BNF definition for `code_challenge`](https://datatracker.ietf.org/doc/html/rfc7636#section-4.2):

```
   code-challenge = 43*128unreserved
   unreserved = ALPHA / DIGIT / "-" / "." / "_" / "~"
   ALPHA = %x41-5A / %x61-7A
   DIGIT = %x30-39
```

Currently [`isValidCodeChallenge`](https://github.com/Taproot/indieauth/blob/main/src/functions.php#L219) seems to only allow `/^[A-Za-z0-9_-]+$/`. It should also allow `.` and `~`.

**Comment by barnabywalters** [comment]
Thanks! Fixed in d65d60581
